由計時器啟動
Running as SYSTEM
建置中 工作區 C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1
[auto_v1.1] $ cmd /c call C:\Windows\TEMP\jenkins16941552641339022178.bat

C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1>C:

C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1>pytest -vs test_demo.py -s -q --alluredir target/allure-results 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --alluredir target/allure-results
  inifile: None
  rootdir: C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1


C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1>exit 4 
Build step '執行 Windows 批次指令' marked build as failure
[auto_v1.1] $ C:\allure-2.20.1\bin\allure.bat generate C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1\target\allure-results -c -o C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1\target\allure-report
Report successfully generated to C:\ProgramData\Jenkins\.jenkins\workspace\auto_v1.1\target\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE
